spring:
  application:
    name: inventory-service
  profiles:
    active: seed
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  docker:
    compose:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

problem-details:
  base-uri: https://wastecoder.com/problems
